"use client";

import { Document, Page, Text, View, StyleSheet, Image } from "@react-pdf/renderer";
import type { DateRangeKey } from "@/components/export/ExportService";
import { SECTION_IDS, SECTION_LABELS } from "@/components/brand-analysis/BrandAnalysisNav";
import { extractParagraphs, dedupeParagraphs } from "@/components/brand-analysis/utils";

const styles = StyleSheet.create({
  page: {
    paddingTop: 40,
    paddingBottom: 40,
    paddingLeft: 40,
    paddingRight: 40,
    fontSize: 10,
    fontFamily: "Helvetica",
  },
  header: {
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#cccccc",
    borderBottomStyle: "solid",
    paddingBottom: 8,
  },
  titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  reportTitle: {
    fontSize: 16,
    fontWeight: 700,
  },
  metaText: {
    fontSize: 9,
    color: "#555555",
  },
  section: {
    width: "100%",
    marginTop: 18,
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 8,
  },
  paragraph: {
    fontSize: 11,
    lineHeight: 1.6,
    marginBottom: 10,
  },
  list: {
    width: "100%",
    marginTop: 2,
    marginBottom: 4,
  },
  listItem: {
    fontSize: 10,
    lineHeight: 1.5,
    marginBottom: 4,
  },
  chartImage: {
    marginTop: 8,
    marginBottom: 8,
    width: "100%",
    height: 120,
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 40,
    right: 40,
    fontSize: 8,
    color: "#777777",
    flexDirection: "row",
    justifyContent: "space-between",
  },
});

type BrandAnalysisReportProps = {
  companyName: string;
  dateRange: DateRangeKey;
  exportedAtIso: string;
  analysis: Record<string, unknown>;
  // Optional chart images per section: { [sectionId]: string[] of data URLs }
  chartsBySection?: Record<string, string[]>;
};

function formatDateRangeLabel(range: DateRangeKey): string {
  if (range === "last_7_days") return "Last 7 days";
  if (range === "last_28_days") return "Last 28 days";
  if (range === "last_90_days") return "Last 90 days";
  return range;
}

export function BrandAnalysisReport({
  companyName,
  dateRange,
  exportedAtIso,
  analysis,
  chartsBySection = {},
}: BrandAnalysisReportProps) {
  const exportedAt = new Date(exportedAtIso);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <View style={styles.titleRow}>
            <Text style={styles.reportTitle}>Brand Analysis Report</Text>
            <Text style={styles.metaText}>MarkGrid</Text>
          </View>
          <View style={{ marginTop: 4 }}>
            <Text style={styles.metaText}>Company: {companyName}</Text>
            <Text style={styles.metaText}>
              Date range: {formatDateRangeLabel(dateRange)}
            </Text>
            <Text style={styles.metaText}>
              Exported at: {exportedAt.toISOString()}
            </Text>
          </View>
        </View>

        {/* Sections */}
        {SECTION_IDS.map((id) => {
          const raw = (analysis as Record<string, unknown>)[id];
          const paragraphs = dedupeParagraphs(extractParagraphs(raw));
          if (!paragraphs.length && !chartsBySection[id]?.length) return null;

          const sectionTitle = SECTION_LABELS[id];

          return (
            <View key={id} style={styles.section}>
              <Text style={styles.sectionTitle} wrap>
                {sectionTitle}
              </Text>
              {paragraphs.map((p, idx) => (
                <Text key={idx} style={styles.paragraph} wrap>
                  {p}
                </Text>
              ))}
              {chartsBySection[id]?.length ? (
                <View>
                  {chartsBySection[id]!.map((src, idx) => (
                    <Image
                      key={idx}
                      src={src}
                      style={styles.chartImage}
                    />
                  ))}
                </View>
              ) : null}
            </View>
          );
        })}

        {/* Footer */}
        <View
          style={styles.footer}
          fixed
        >
          <Text>Generated by MarkGrid</Text>
          <Text
            render={({ pageNumber, totalPages }) =>
              `Page ${pageNumber} of ${totalPages}`
            }
          />
        </View>
      </Page>
    </Document>
  );
}

