"use client";

import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    paddingTop: 40,
    paddingBottom: 40,
    paddingLeft: 40,
    paddingRight: 40,
    fontSize: 10,
    fontFamily: "Helvetica",
  },
  header: {
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#cccccc",
    borderBottomStyle: "solid",
    paddingBottom: 8,
  },
  titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  reportTitle: {
    fontSize: 16,
    fontWeight: 700,
  },
  metaText: {
    fontSize: 9,
    color: "#555555",
  },
  section: {
    width: "100%",
    marginTop: 18,
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 8,
  },
  paragraph: {
    fontSize: 11,
    lineHeight: 1.6,
    marginBottom: 10,
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 40,
    right: 40,
    fontSize: 8,
    color: "#777777",
    flexDirection: "row",
    justifyContent: "space-between",
  },
});

type GenericReportProps = {
  userName: string;
  reportType: string;
  dateRange: string;
  exportedAtIso: string;
};

export function GenericReport({
  userName,
  reportType,
  dateRange,
  exportedAtIso,
}: GenericReportProps) {
  const exportedAt = new Date(exportedAtIso);

  const readableType =
    reportType.charAt(0).toUpperCase() + reportType.slice(1).toLowerCase();

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <View style={styles.titleRow}>
            <Text style={styles.reportTitle}>MarkGrid Reports</Text>
            <Text style={styles.metaText}>{userName}</Text>
          </View>
          <View style={{ marginTop: 4 }}>
            <Text style={styles.metaText}>Report type: {readableType}</Text>
            <Text style={styles.metaText}>Date range: {dateRange}</Text>
            <Text style={styles.metaText}>
              Exported at: {exportedAt.toISOString()}
            </Text>
          </View>
        </View>

        {/* Intro section */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>{readableType} overview</Text>
          <Text style={styles.paragraph}>
            This report summarizes key MarkGrid insights for the selected report
            type and time period. Use it as a high-level snapshot alongside the
            interactive dashboards in the app.
          </Text>
        </View>

        {/* Placeholder content */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Details</Text>
          <Text style={styles.paragraph}>
            Detailed metrics and breakdowns for this report type are not wired into
            the PDF yet, but are fully available in the MarkGrid UI. Future
            versions of this export can include specific tables and charts once the
            underlying data model is finalized.
          </Text>
        </View>

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text>Generated by MarkGrid</Text>
          <Text
            render={({ pageNumber, totalPages }) =>
              `Page ${pageNumber} of ${totalPages}`
            }
          />
        </View>
      </Page>
    </Document>
  );
}

