"use client";

import type { ReactNode } from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";

export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 40,
    paddingBottom: 40,
    paddingHorizontal: 40,
    fontSize: 11,
    fontFamily: "Helvetica",
    color: "#111111",
  },
  header: {
    borderBottomWidth: 1,
    borderBottomColor: "#e5e5e5",
    borderBottomStyle: "solid",
    paddingBottom: 12,
    marginBottom: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  logo: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#0070ff",
  },
  headerMeta: {
    textAlign: "right",
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 4,
  },
  headerMetaLine: {
    fontSize: 10,
    marginTop: 2,
  },
  content: {
    flexGrow: 1,
  },
  section: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: "bold",
    marginBottom: 6,
  },
  sectionDivider: {
    borderBottomWidth: 1,
    borderBottomColor: "#eeeeee",
    borderBottomStyle: "solid",
    marginBottom: 8,
  },
  paragraph: {
    fontSize: 11,
    lineHeight: 1.4,
    marginBottom: 4,
  },
  footer: {
    position: "absolute",
    bottom: 28,
    left: 40,
    right: 40,
    fontSize: 9,
    textAlign: "center",
    color: "#999999",
  },
});

interface PDFLayoutProps {
  title: string;
  companyName?: string;
  exportDate?: string;
  dateRangeLabel?: string;
  children: ReactNode;
}

export function PDFLayoutDocument({
  title,
  companyName,
  exportDate,
  dateRangeLabel,
  children,
}: PDFLayoutProps) {
  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        <View style={pdfStyles.header}>
          <Text style={pdfStyles.logo}>MarkGrid</Text>
          <View style={pdfStyles.headerMeta}>
            <Text style={pdfStyles.headerTitle}>{title}</Text>
            {companyName ? (
              <Text style={pdfStyles.headerMetaLine}>{companyName}</Text>
            ) : null}
            {exportDate ? (
              <Text style={pdfStyles.headerMetaLine}>
                Exported on {exportDate}
              </Text>
            ) : null}
            {dateRangeLabel ? (
              <Text style={pdfStyles.headerMetaLine}>
                Date range: {dateRangeLabel}
              </Text>
            ) : null}
          </View>
        </View>
        <View style={pdfStyles.content}>{children}</View>
        <Text style={pdfStyles.footer}>Generated by MarkGrid</Text>
      </Page>
    </Document>
  );
}

